console.clear();
var teclado = require('prompt-sync')();
var ola = teclado("Digite uma congratula\u00E7\u00E3o: ");
var nome = teclado("Digite seu nome: ");
var passaTempo = teclado("Digite um passatempo: ");
var diaAniversario = teclado("Digite o dia do anivers\u00E1rio: ");
var mesAniversario = teclado("Digite o m\u00EAs do anivers\u00E1rio: ");
var anoAniversario = teclado("Digite o ano do anivers\u00E1rio: ");
console.log("".concat(ola));
console.log("Meu nome \u00E9 ".concat(nome, ", nascido no dia ").concat(diaAniversario));
console.log("de ".concat(mesAniversario, " de ").concat(anoAniversario, ","));
console.log("meu atual passatempo \u00E9 ".concat(passaTempo));
